const COURSE = {
    LOAD: 'COURSE_LOAD',
    LOAD_SUCCESS: 'COURSE_LOAD_SUCCESS',
    COURSE_DELETE: 'COURSE_DELETE',
    COURSE_DELETE_UTIL: 'COURSE_DELETE_UTIL',
    COURSE_EDIT: 'COURSE_EDIT',
    LOAD_FAIL: 'COURSE_LOAD_FAIL',
    ADD_COURSE: 'ADD_COURSE',
    ADD_COURSE_UTIL: 'ADD_COURSE_UTIL'
}

const AUTHOR = {
    LOAD: 'AUTHOR_LOAD',
    LOAD_SUCCESS: 'AUTHOR_LOAD_SUCCESS',
    LOAD_FAIL: 'AUTHOR_LOAD_FAIL',
    ADD_COURSE: 'ADD_AUTHOR'
}

const URL = {
    COURSE_URL: "http://localhost:3002/courses",
    AUTHOR_URL: "http://localhost:3002/authors"
}


export { COURSE, URL, AUTHOR }
